# EXAMPLE USAGE:
#
#   Refer for explanation to following link:
#   https://lefthook.dev/configuration/
#

pre-push:
  commands:
    test:
      run: go test ./...

pre-commit:
  commands:
    golangci-lint:
      run: go tool golangci-lint run
    cloc:
      only:
        - run: command -v cloc > /dev/null
      run: cloc . --quiet --hide-rate

commit-msg:
  commands:
    conventional-commit:
      run: |
        commit_msg=$(cat {1})
        pattern="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^)]+\))?: [^ ].+"
        if ! echo "$commit_msg" | grep -qE "$pattern"; then
          echo "❌ Commit message does not follow Conventional Commits format"
          echo ""
          echo "Expected format: <type>[optional scope]: <description>"
          echo ""
          echo "Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
          echo ""
          echo "Example: feat(auth): add login functionality"
          exit 1
        fi
